//
//  ContentView2.swift
//  TaskTest
//
//  Created by tongbin的mac on 2023/11/17.
//

import SwiftUI
 

struct User: Identifiable, Hashable {
    let id: UUID
    let name: String
    let section: String

    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }

    static func ==(lhs: User, rhs: User) -> Bool {
        lhs.id == rhs.id
    }
}

struct ContentView2: View {
    let users = [
        User(id: UUID(), name: "John", section: "Section 1"),
        User(id: UUID(), name: "Jane", section: "Section 1"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Mike", section: "Section 2"),
        User(id: UUID(), name: "Emily", section: "Section 2"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),

        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"), User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"), User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"), 
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"), User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"), 
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"), 
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"), User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"), User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"), User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"), 
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        User(id: UUID(), name: "Jane", section: "Section 3"),
        

    ]

    var sections: [String] {
        Array(Set(users.map { $0.section })).sorted()
    }

    @State private var selectedUsers = Set<User>()
    private var gridItemLayout = [GridItem(.adaptive(minimum: 60,maximum: 60))]

    var body: some View {
            ScrollView {
                LazyVGrid(columns : gridItemLayout ){
                    ForEach(sections, id: \.self) { section in
                        let filteredUsers = users.filter { $0.section == section }
                        Section(header: Text(section)) {
                            ForEach(filteredUsers, id: \.self) { user in
                                ZStack(alignment: .topTrailing) {
                                    Text(user.name)
                                        .padding()
                                        .background(selectedUsers.contains(user) ? Color.blue : Color.white)
                                        .cornerRadius(10)
                                        .onTapGesture {
                                            if selectedUsers.contains(user) {
                                                selectedUsers.remove(user)
                                            } else {
                                                selectedUsers.insert(user)
                                            }
                                        }
                                    if selectedUsers.contains(user) {
                                        Image(systemName: "checkmark.circle.fill")
                                            .foregroundColor(.white)
                                            .padding()
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
     
}

#Preview {
    ContentView2()
}
